services:


  postgres2:
    image: postgres:latest
    container_name: postgres2
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: casbin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - twitter


  api-service:
    build: .
    container_name: api-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres2
    networks:
      - twitter

volumes:
  postgres-data:

networks:
  twitter:
    external: true